---
title: "Parametric vs NoParametric"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{toy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ARIpermutation)
```

```{r}

m <- 1e3 #number of variables
n <- 20 #number of observations
pi0 <- 0.4 #Proportion of true null hypotheses
B <- 1e4 #number of permutation
rhos <- seq(0,0.9,0.10) #Level of equi-correlation between pairs of variables
SNR <-5 #Signal to noise ratio. 
alpha <- 0.2 #alpha level
delta <- seq(1,500,10)
family = "Simes"
```

```{r}
simEC <- function(m,rho,n,pi0,SNR){
  
  out <- gaussianSamples(m,rho,n,pi0,SNR)
  H <- out$H
  X <-out$X
  res <- ARIpermutation::testByRandomization(X,B)
  Test <- cbind(res$T,res$T0)
  P <- cbind(res$p,res$p0)
  P <- t(P)
  Psort <- rowSortC(P)
  lambdaSimes <- ARIpermutation::lambdaOpt(pvalues = P,family = family,ct = ct,alpha = alpha,delta = 7)
  cvSimes <- ARIpermutation::cv(pvalues = Psort,family = family,alpha = alpha,lambda = lambdaSimes,ct = ct,delta = 7)
  ec <- sansSouci:::empiricalCoverage(cvSimes, Test)
  out <- as.data.frame(cbind(cvSimes, res$p, 
                             rep(n = length(cv), ec), H))
  colnames(out) <- c("CriticalValue", 
                     "Pvalues", 
                     "EC", "H"
  )
  return(out)
}
```

```{r}

out <- sapply(c(1:length(rhos)), function(x) simEC(m,rhos[x],n,pi0,SNR),simplify = FALSE)

cv <- sapply(c(1:length(rhos)), function(x) out[[x]]$CriticalValue)
Pvalues <- sapply(c(1:length(rhos)), function(x) out[[x]]$Pvalues)
EC <- sapply(c(1:length(rhos)), function(x) out[[x]]$EC)
H <- sapply(c(1:length(rhos)), function(x) out[[x]]$H)
H <- H[,1]

discoveriesPerm <- sapply(c(1:length(rhos)), function(x) dI(ix = c(1:900),cv = cv[,x],praw = Pvalues[,x]))

discoveriesHommel <- sapply(c(1:length(rhos)), function(x) discoveries(hommel(Pvalues[,x]),ix = c(1:900)))

plot(rhos,discoveriesPerm, ylim = c(420,500), type = "l", xlab = expression(rho), ylab = "Discoveries")
lines(rhos,discoveriesHommel, col = 'red')

```

```{r}
plot(rhos,unique(EC), type = "l", xlab = expression(rho), ylab = "Empirical Coverage", ylim = c(0.75,1.1))
abline(h = 0.8)
ses <- sqrt(unique(EC)*(1-unique(EC))/B)
```

```{r}
id <- 8
p <- sort(Pvalues[,id])
R = sapply(p, function(t) sum(p <=t)) 
Bperm = sapply(1:length(p), function(i) i-dI(ix = c(1:i),cv = cv[,id],praw = Pvalues[,id]))       
Bpar = sapply(1:length(p), function(i) i-discoveries(hommel(Pvalues[,id], simes = TRUE), ix=1:i, alpha=alpha))

H0 <- which(H == 0)
o <- order(Pvalues[,id], decreasing = TRUE)
V <- cumsum(o %in% H0)

plot(R,Bpar/pmax(1,R), type="l", col='red', lwd=2, ylab = "upper bound FDP", xlab='number of rejection', ylim = c(0,1))
lines(R,Bperm/pmax(1,R), type="l", col=1, lwd=2)
lines(R,V/pmax(1,R), type="l", lwd=2, col = 'blue')
legend("bottomright", legend=c("Perm", "Par",  "True"), col=c("black", "red", "blue"), lty = c(rep(1,3)),lwd = c(rep(1,3)))
```


