---
title: "Plot simulate data"
author: "Angela Andreella"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{toy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
# knitr::opts_chunk$set(
#   collapse = TRUE,
#   comment = "#>"
# )
```

```{r setup}
library(ARIpermutation)
library(hommel)
library(ggplot2)
```

```{r}
m <- 1e3 #number of variables
n <- 20 #number of observations
pi0 <- 0.9 #Proportion of true null hypotheses
B <- 999 #number of permutation
rho <- 0 #Level of equi correlation between pairs of variables
alpha <- 0.05 #alpha level
power <- 0.8
delta <- 0
ct = c(0,1)
```


Create simulate data 

```{r}
X <-simulateData(pi0,m,n, rho, power = power, alpha = alpha, rho = rho)
X <- t(X)
res <- ARIpermutation::signTest(X,B)
Test <- cbind(res$Test,res$Test_H0)
P <- cbind(res$pv,res$pv_H0)
```

So, we plot the null distribution

```{r}
ARIpermutation::plotNullDistribution(family = NULL,alpha = alpha, ct = ct,P = P,B = B)
```

We add the Simes critical values:

```{r}
ARIpermutation::plotNullDistribution(family = "simes", alpha = alpha, ct = ct,P = P,B = B, delta = delta)
```

```{r}
ARIpermutation::plotNullDistribution(family = "finner", alpha = alpha, ct = ct,P = P,B = B, delta = delta)
```


