---
title: "Parametric vs NoParametric"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{toy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(ARIpermutation)
library(hommel)
library(ggplot2)
m <- 1e3 #number of variables
n <- 20 #number of observations
pi0 <- 0.5 #Proportion of true null hypotheses
B <- 1e3 #number of permutation
rhos <- seq(0,0.9,0.10) #Level of equi-correlation between pairs of variables
SNR <-5 #Signal to noise ratio. 
alpha <- 0.1 #alpha level
delta <- seq(1,500,10)
delta <- 0
family = "Simes"
ct = c(0,1)
```

```{r}
simEC <- function(m,rho,n,pi0,SNR){
  
  out <- sansSouci::gaussianSamples(m,rho,n,pi0,SNR)
  H <- out$H
  X <-out$X
  res <- ARIpermutation::signTest(X,B)
  Test <- cbind(res$Test,res$Test_H0)
  P <- cbind(res$pv,res$pv_H0)
  P <- t(P)
  Psort <- t(apply(P,1,sort))
  lambdaSimes <- ARIpermutation::lambdaOpt(pvalues = P,family = family,ct = ct,alpha = alpha,delta = 0)
  cvSimes <- ARIpermutation::cv(pvalues = Psort,family = family,alpha = alpha,lambda = lambdaSimes,ct = ct,delta = 0)
  ec <- sansSouci:::empiricalCoverage(cvSimes, Test)
  out <- as.data.frame(cbind(cvSimes, res$pv, 
                             rep(n = length(cv), ec), H))
  colnames(out) <- c("CriticalValue", 
                     "Pvalues", 
                     "EC", "H"
  )
  return(out)
}
```

```{r}

out <- sapply(c(1:length(rhos)), function(x) simEC(m = m,rho = rhos[x],n = n,pi0 = pi0,SNR = SNR),simplify = FALSE)

cv <- sapply(c(1:length(rhos)), function(x) out[[x]]$CriticalValue)
Pvalues <- sapply(c(1:length(rhos)), function(x) out[[x]]$Pvalues)
EC <- sapply(c(1:length(rhos)), function(x) out[[x]]$EC)
H <- sapply(c(1:length(rhos)), function(x) out[[x]]$H)
H <- H[,1]

discoveriesPerm <- sapply(c(1:length(rhos)), function(x) ARIpermutation::dI(ix = c(1:1000),cv = cv[,x],praw = Pvalues[,x]))

discoveriesHommel <- sapply(c(1:length(rhos)), function(x) hommel::discoveries(hommel(Pvalues[,x]),ix = c(1:1000)))


ggplot() +
   geom_line(aes(x = rhos, y = discoveriesPerm, colour = "Nonparametric"))+ 
   geom_line(aes(x = rhos, y = discoveriesHommel, colour = "Parametric")) +
   xlab(expression(rho)) +
   ylab('number of True Discoveries')  + theme(legend.title=element_blank())

```

```{r}

ggplot() +
   geom_line(aes(x = rhos[1:10], y = unique(EC)[1:10]))+ ylim(0.75,1.005) +
   geom_line(aes(x = rhos[1:10], y = rep(0.8, 10)), col = "red") +
   xlab(expression(rho)) +
   ylab('Empirical Coverage')

ses <- sqrt(unique(EC)*(1-unique(EC))/B)
```

```{r}
id <- 8
p <- sort(Pvalues[,id])
R = sapply(p, function(t) sum(p <=t)) 
load(system.file("extdata/vignettes_data", "Bperm.RData", package = "ARIpermutation"))

#Bperm = sapply(1:length(p), function(i) i-ARIpermutation::dI(ix = c(1:i),cv = cv[,id],praw = Pvalues[,id]))       
Bpar = sapply(1:length(p), function(i) i-hommel::discoveries(hommel(Pvalues[,id], simes = TRUE), ix=1:i, alpha=alpha))

H0 <- which(H == 0)
o <- order(Pvalues[,id], decreasing = TRUE)
V <- cumsum(o %in% H0)

ggplot() +
   geom_line(aes(x = R, y = (R-Bpar)/pmax(1,R), colour = "Parametric TDP"))+ ylim(0,0.5) +
   geom_line(aes(x = R, y = (R-Bperm)/pmax(1,R), colour = "Permation TDP")) +
  geom_line(aes(x = R, y = (R-V)/pmax(1,R), colour = "True TDP") )+
   xlab("Number of rejections") +
   ylab('True Discoveries Proportion')  + theme(legend.title=element_blank())

```

```{r}
out <- sansSouci::gaussianSamples(m,rho=0.7,n,pi0,SNR)
H <- out$H
X <-out$X
res <- ARIpermutation::signTest(X,B)
Test <- res$Test
data <- as.data.frame(cbind(Test,H))
colnames(data) <- c("Test", "Hyp")
data$Hyp <- ifelse(data$Hyp==0, "Null", "Alternative")
data$Hyp <- as.factor(data$Hyp)
ggplot(data,aes(x=c(1:m), y=Test, color=Hyp)) +
  geom_point() + ylab("Test") + xlab("Index hyp")

```

