# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colSortC <- function(X) {
    .Call(`_ARIpermutation_colSortC`, X)
}

lambdaCalibrate <- function(X, alpha, delta, family) {
    .Call(`_ARIpermutation_lambdaCalibrate`, X, alpha, delta, family)
}

permDiscoveries <- function(ix, cv, praw) {
    .Call(`_ARIpermutation_permDiscoveries`, ix, cv, praw)
}

permT <- function(X, B, label) {
    .Call(`_ARIpermutation_permT`, X, B, label)
}

rowSortC <- function(X) {
    .Call(`_ARIpermutation_rowSortC`, X)
}

signFlip <- function(X, B) {
    .Call(`_ARIpermutation_signFlip`, X, B)
}

