# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowSortC <- function(X) {
    .Call(`_ARIpermutation_rowSortC`, X)
}

signFlip <- function(X, B) {
    .Call(`_ARIpermutation_signFlip`, X, B)
}

varBySignFlipping <- function(X, B) {
    .Call(`_ARIpermutation_varBySignFlipping`, X, B)
}

meanBySignFlipping <- function(X, B) {
    .Call(`_ARIpermutation_meanBySignFlipping`, X, B)
}

